package on2015_03.on2015_03_02_Codeforces_Round__294__Div__2_.C___A_and_B_and_Team_Training;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2015_03/on2015_03_02_Codeforces_Round__294__Div__2_/C___A_and_B_and_Team_Training/C - A and B and Team Training.task"))
			Assert.fail();
	}
}
