package on2015_03.on2015_03_29_Codeforces_Round__297__Div__2_.A___Vitaliy_and_Pie;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2015_03/on2015_03_29_Codeforces_Round__297__Div__2_/A___Vitaliy_and_Pie/A - Vitaliy and Pie.task"))
			Assert.fail();
	}
}
